In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("FashionDataset.csv") # downloaded from kaggle:

In [7]:
df.head()

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30758 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30758 non-null  int64
 1   BrandName   30758 non-null  str
 2   Deatils     30758 non-null  str
 3   Sizes       30758 non-null  str
 4   MRP         30758 non-null  str
 5   SellPrice   30758 non-null  str
 6   Discount    30758 non-null  str
 7   Category    30758 non-null  str
dtypes: int64(1), str(7)
memory usage: 1.9 MB

In [11]:
df.shape

(30758, 8)

In [12]:
df.columns

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='str')

In [ ]:
# Deleting redundant columns
df = df.drop(columns = "Unnamed: 0")
df.head()

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [17]:
df = df.rename(columns = {"Deatils" : "Details"})
df.head()

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [ ]:
df.loc[df.duplicated()]
df = df.drop_duplicates()

In [21]:
df.duplicated().sum()

np.int64(0)

In [24]:
# Fixing the index since rows were deleted
df = df.reset_index().drop(columns = "index")

In [28]:
# Removing NA values
df.isna().sum
df = df.dropna()

In [30]:
df["BrandName"] = df["BrandName"].apply(lambda x : x.capitalize())
df["Details"] = df["Details"].apply(lambda x : x.capitalize())

In [35]:
df["Sizes"].loc[27926]
# type(df["Sizes"].loc[27926])
# need to remove the Nan values

'Nan'

In [38]:
df

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
27926,Shaya by caratlane,The wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
27927,Swarovski,Crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
27928,Jewelz,Ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
27929,Estelle,Womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
27930,Estelle,Womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [40]:
df["Sizes"] = df["Sizes"].apply(lambda x : "NA VALUED" if x == "Nan" else x)

In [42]:
df

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
27926,Shaya by caratlane,The wing woman clover charm necklace,NA VALUED,Nan,1250,Nan,Jewellery-Women
27927,Swarovski,Crystal stylish womens rodhium earrings,NA VALUED,Nan,8950,Nan,Jewellery-Women
27928,Jewelz,Ethnic gold plated jhumki earrings,NA VALUED,Rs\n1839,643,65% off,Jewellery-Women
27929,Estelle,Womens gold plated double line fancy white and...,NA VALUED,Nan,2799,Nan,Jewellery-Women
27930,Estelle,Womens gold plated bridge designer mangalsutra...,NA VALUED,Nan,1899,Nan,Jewellery-Women

In [43]:
df[df["Sizes"] != "NA VALUED"]

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24344,Swiss eagle,Womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
24731,Lawman watches,Womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
25791,Lawman watches,Womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women
26028,Miu miu,Eau de parfum - 50 ml,Size:Error Size,Nan,6100,Nan,Fragrance-Women
26078,Miu miu,Eau de parfum - 30 ml,Size:Error Size,Nan,4400,Nan,Fragrance-Women

In [49]:

for column in df.columns:
    rows_to_keep = (df[column] != 'Nan') & (df[column] != 'NA VALUED')
    df = df[rows_to_keep]

df

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24141,Lemon & pepper,Womens casual wear buckle closure flats - navy,"Size:36,37,38,39,40",Rs\n2999,1499,50% off,Footwear-Women
24142,Haute curry,Womens casual wear slip on heels - black,"Size:36,37,38,39,40",Rs\n2199,1099,50% off,Footwear-Women
24344,Swiss eagle,Womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
24731,Lawman watches,Womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
25791,Lawman watches,Womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women

In [51]:
df = df.reset_index().drop(columns = "index")
df

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
17926,Lemon & pepper,Womens casual wear buckle closure flats - navy,"Size:36,37,38,39,40",Rs\n2999,1499,50% off,Footwear-Women
17927,Haute curry,Womens casual wear slip on heels - black,"Size:36,37,38,39,40",Rs\n2199,1099,50% off,Footwear-Women
17928,Swiss eagle,Womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
17929,Lawman watches,Womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
17930,Lawman watches,Womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women

In [52]:
df.to_csv("Cleaned_FashionDataset.csv", index = False)

In [53]:
pd.read_csv("Cleaned_FashionDataset.csv")

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
17926,Lemon & pepper,Womens casual wear buckle closure flats - navy,"Size:36,37,38,39,40",Rs\n2999,1499,50% off,Footwear-Women
17927,Haute curry,Womens casual wear slip on heels - black,"Size:36,37,38,39,40",Rs\n2199,1099,50% off,Footwear-Women
17928,Swiss eagle,Womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
17929,Lawman watches,Womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
17930,Lawman watches,Womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women